# -*- coding: utf-8 -*-
"""A/B Testingipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wbza2VVqLHmleKb63Vr0HT1nG789B-87

#2.1 Load and inspect
"""

import pandas as pd
from scipy import stats
import numpy as np
df = pd.read_csv("DATASET.csv")

print(df.head())
print(df.info())
print(df.describe())

"""#2.2 Create a session-level conversion flag

We want one row per (session_id, variation, platform) with:

converted = 1 if that session ever had a successful order,

0 otherwise.
"""

df = df.dropna()
display(df.value_counts())



"""#2.3 Map numeric variation to readable group names (A/B)"""

# Parse datetime
df["datetime_event"] = pd.to_datetime(df["datetime_event"])

print(df.head())
print(df.dtypes)

# Check variations present
print("Variations:", df["variation"].unique())

# Check what final_order_status values exist
print(df["final_order_status"].value_counts(dropna=False).head(20))

# Check event types (for funnel/extra analysis)
print(df["event_type"].value_counts().head(20))

"""#2.4 Overall A/B test on conversion rate"""

# 1. Flag successful order events
success_statuses = ["successful"]  # <-- change to match your data
df["is_success_event"] = df["final_order_status"].isin(success_statuses).astype(int)

# 2. Aggregate to session level
session_df = (
    df
    .groupby(["session_id", "variation", "platform"], as_index=False)
    .agg(
        converted=("is_success_event", "max")  # 1 if any success in that session
    )
)

print(session_df.head())
print(session_df["variation"].value_counts())

"""#Two-proportion z-test

"""

# Identify control and treatment based on variation values
var_values = sorted(session_df["variation"].unique())
control_var = var_values[0]
treatment_var = var_values[1] if len(var_values) > 1 else var_values[0]

session_df["group"] = np.where(
    session_df["variation"] == control_var, "control", "treatment"
)

print(session_df["group"].value_counts())

"""#95% confidence interval"""

control = session_df[session_df["group"] == "control"]
treatment = session_df[session_df["group"] == "treatment"]

n_control = len(control)
n_treat = len(treatment)

conv_control = control["converted"].mean()
conv_treat = treatment["converted"].mean()

print(f"Control sessions: {n_control}, conversion rate: {conv_control:.4f}")
print(f"Treatment sessions: {n_treat}, conversion rate: {conv_treat:.4f}")

# Lift
absolute_lift = conv_treat - conv_control
relative_lift = absolute_lift / conv_control if conv_control > 0 else np.nan

print(f"Absolute lift (T - C): {absolute_lift:.4f}")
print(f"Relative lift: {relative_lift * 100:.2f}%")

"""#3. Optional: Break down by platform"""

# successes
success_control = control["converted"].sum()
success_treat = treatment["converted"].sum()

# pooled proportion
p_pool = (success_control + success_treat) / (n_control + n_treat)

# standard error
se = np.sqrt(p_pool * (1 - p_pool) * (1/n_control + 1/n_treat))

# z-score
z = (conv_treat - conv_control) / se

# two-tailed p-value
p_value = 2 * (1 - stats.norm.cdf(abs(z)))

print(f"z-score: {z:.4f}")
print(f"p-value: {p_value:.4f}")

alpha = 0.05
if p_value < alpha:
    print("Result: Statistically significant difference. Reject H0.")
else:
    print("Result: Not statistically significant. Fail to reject H0.")



z_crit = stats.norm.ppf(1 - alpha/2)  # ~1.96 for 95%

se_diff = np.sqrt(
    conv_control * (1 - conv_control) / n_control +
    conv_treat * (1 - conv_treat) / n_treat
)

ci_lower = (conv_treat - conv_control) - z_crit * se_diff
ci_upper = (conv_treat - conv_control) + z_crit * se_diff

print(f"95% CI for (Treatment - Control): [{ci_lower:.4f}, {ci_upper:.4f}]")

platform_summary = (
    session_df
    .groupby(["platform", "group"])["converted"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "sessions", "mean": "conversion_rate"})
)

print(platform_summary)